config/routes.rb
Rails.application.routes.draw do
  root 'home#about'
  get 'home/top'
  devise_for :users

  resources :users, only: [:show, :edit, :update, :withdraw, :destroy] do
    get :withdraw, on: :member
    resource :relationships, only: [:create, :destroy]
  end
  resources :posts do
    resource :favorites, only: [:index, :create, :destroy]
    resource :post_comments, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_posts, through: :favorites, source: 'post'

  attachment :image

  validates :title, presence: true
  validates :body, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy

  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_posts, through: :favorites, source: 'post', dependent: :destroy
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人

  attachment :pro_image

  validates :name, presence: true
  validates :email, presence: true
  validates :introdution, length: { in: 3..50 }, allow_blank: true

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_search

  private

  def after_sign_in_path_for(resource)
    home_top_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def set_search
    @search = Post.ransack(params[:q])
    @posts = @search.result.page(params[:page])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    if user_signed_in?
      favorite = @post.favorites.new(user_id: current_user.id)
      favorite.save
    else
      redierect_to new_user_session_path
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    if user_signed_in?
      favorite = current_user.favorites.find_by(post_id: @post.id)
      favorite.destroy
    else
      redeirect_to new_user_session_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about; end

  def top
    @posts = Post.find(Favorite.group(:post_id).order('count(post_id) desc').limit(4).pluck(:post_id))
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    @post_comment = @post.post_comments.new(post_comment_params)
    @post_comment.user_id = current_user.id
    if @post_comment.save
    else
      @post_comments = PostComment.where(id: @post)
    end
  end

  def destroy
    @post_comment = PostComment.find(params[:post_id])
    @post = @post_comment.post
    if @post_comment.user != current_user
      redirect_back(fallback_location: posts_path)
    end
    @post_comment.destroy
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def index; end

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
    @post_comments = @post.post_comments.order(created_at: "DESC")
  end

  def edit
    @post = Post.find(params[:id])
    if @post.user_id != current_user.id
      redirect_to posts_path
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.user_id == current_user.id
      @post.destroy
      redirect_to posts_path
    else
      @posts = Post.all
      render "index"
    end
  end

  private

  def post_params
    params.require(:post).permit(:user_id, :title, :body, :image)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!

  def follower
    @user = User.find(params[:user_id])
    @users = @user.following_user.page(params[:page]).reverse_order
  end

  def followed
    @user = User.find(params[:user_id])
    @users = @user.follower_user.page(params[:page]).reverse_order
  end

  def create
    current_user.follow(params[:user_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order(created_at: "DESC").page(params[:page])
    @users = @user.following_user.page(params[:page])
    @followers = @user.follower_user.page(params[:page])
    @favorites = @user.favorited_posts.page(params[:page])
  end

  def edit
    @user = User.find(params[:id])
    if current_user != @user
      redirect_to user_path(@user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  def withdraw
    @user = User.find(params[:id])
    if current_user != @user
      redirect_to user_path(current_user)
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "またのご利用をお待ちしております。"
    reset_session
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :pro_image, :introdution)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/create.js.erb
$(".post_favorite_<%= @post.id %>").html("<%= j(render 'posts/favorite', post: @post ) %>");

app/views/favorites/destroy.js.erb
$(".post_favorite_<%= @post.id %>").html("<%= j(render 'posts/favorite', post: @post ) %>");

app/views/home/about.html.erb
<div class="containerfluid">
  <div id="global">
    <div class="about-text">
      <span class="about-title">Care tool</span>
      <p>このサイトは、介護の悩み相談サイトです。介護に便利な道具・ちょっとした悩み等を意見交換ができます。</p>
    </div>
  </div>
</div>

app/views/home/top.html.erb
<div class="clearfix">
  <div class="main-visual"><div class="App-name">Care tool</div></div>
</div>

<main>
  <div class="link-box">
    <div><%= link_to "このサイトについて", root_path %></div>
    <div><%= link_to "記事", posts_path %></div>
  </div>



  <div class="ranking">
    <div class="favorite-rank"><h2>いいねランキング</h2></div>
    <div class="rank-box">
      <% @posts.each.with_index(1) do |post, i| %>
        <div class="rank-item
        ">
          <span class="ranking-num"><%= "#{i}位"%></span>
          <div class="rank-image"><%= attachment_image_tag(post, :image, :fill, 250, 250, fallback: "写真のフリー素材11.jpeg", size: "250x250") %></div>
            <span class="rank-title"><strong><%= link_to post.title , post_path(post.id) %></strong></span>
              <span>作者<%= post.user.name %></span>
          <div class="rank-info">
              <span><%= icon('far', 'comment-dots')%><%= post.post_comments.count %></span>
              <span><%= icon('fas', 'heart') %><%= post.favorites.count %></span>
            </div>
          </div>
      <% end %>
      </div>
    </div>
  </div>
</main>

app/views/layouts/_Sign_in.html.erb
<div class="login-button">
  <% if user_signed_in? %>
    <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn btn-default navbar-right" %>
  <% else %>
    <%= link_to "ログイン", new_user_session_path, class: "btn btn-default navbar-right" %>
  <% end %>
</div>

app/views/layouts/_Sm_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="Sm-navbar">
      <ul class="Sm-nav-list">
        <% if user_signed_in? %>
          <li class="Sm-nav-list-item">
            <%= link_to home_top_path do %>
              <%= icon("fas", "home", class: 'Sm-nav-icon') %><br>
              <span class="Sm-link-text">トップページ</span>
            <% end %>
          </li>
          <li class="Sm-nav-list-item">
            <%= link_to user_path(current_user) do %>
              <%= icon("far", "user", class: 'Sm-nav-icon') %><br>
              <span class="Sm-link-text">マイページ</span>
            <% end %>
          </li>
          <li class="Sm-nav-list-item">
            <%= link_to posts_path do %>
              <%= icon("fas", "file-alt", class: 'Sm-nav-icon') %><br>
              <span class="Sm-link-text">記事一覧</span>
            <% end %>
          </li>
        <% else %>
          <li class="Sm-nav-list-item">
            <%= link_to root_path do %>
              <%= icon("fas", "globe-africa", class: 'Sm-nav-icon') %><br>
              <span class="Sm-link-text">アバウト</span>
            <% end %>
          </li>
          <li class="Sm-nav-list-item">
            <%= link_to posts_path do %>
              <%= icon("fas", "file-alt", class: 'Sm-nav-icon') %><br>
              <span class="Sm-link-text">記事一覧</span>
            <% end %>
          </li>
          <li class="Sm-nav-list-item">
            <%= link_to new_user_registration_path do %>
              <%= icon("fas", "user-plus", class: 'Sm-nav-icon') %><br>
              <span class="Sm-link-text">会員登録</span>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= obj.errors.count %>件のエラーが発生しました。</h3>
    <ul><%= obj.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="footer-link">
      <span class="top_page_link"><%= link_to "トップページ", home_top_path %></span>
      <span><%= link_to "アバウト", root_path %></span>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar-fixed-top">
  <nav class="navbar navbar-default navbar-fixed-top" style="background-color: #009933">
    <%= render "layouts/search", search: @search %>
    <%= render "layouts/Sign_in" %>
    <div id="navi" class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
            <%= link_to "トップページ", home_top_path %>
          </li>
          <li>
            <%= link_to "マイページ", user_path(current_user) %>
          </li>
          <li>
            <%= link_to "記事一覧", posts_path %>
          </li>
          <li class="header-padding">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
          </li>
        <% else %>
          <li>
            <%= link_to "アバウト", root_path %>
          </li>
          <li>
            <%= link_to "記事一覧", posts_path %>
          </li>
          <li>
            <%= link_to "ログイン", new_user_session_path %>
          </li>
          <li>
            <%= link_to "会員登録", new_user_registration_path %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_search.html.erb
<div class="search-form navbar-left">
  <%= search_form_for search do |f| %>
    <div class="input-group col-xs-5">
      <%= f.search_field :title_or_body_or_user_name_cont, placeholder: "キーワード", class: "form-control" %>

      <span class="input-group-btn"><%= f.submit "検索", class: "btn btn-primary" %></span>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <title>Caretool</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" , search: @search %>
    <%= render "layouts/Sm_navbar" %>
      <%= yield %>
      <span id="page-top">
        <a href="#">
          <i class="fas fa-angle-up fa-5x"></i>
        </a>
      </span>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/post_comments/create.js.erb
$("textarea").val("");
$("#post_comment_<%= @post.id %>").html("<%= j(render 'posts/comment', post_comments: @post.post_comments, post: @post ) %>");

app/views/post_comments/destroy.js.erb
$("#post_comment_<%= @post.id %>").html("<%= j(render 'posts/comment', post_comments: @post.post_comments, post: @post ) %>")

app/views/posts/_comment.html.erb
<% post_comments.each do |comment| %>
  <div class="comment-box" id="post_comment_<%= post.id %>">
    <section class="comment-item">
      <div class="comment-head">
        <div>
          <%= attachment_image_tag(comment.user, :pro_image, :fill, 50, 50, fallback: "登録のピクトアイコン1.jpeg", size: "50x50") %>
          <%= link_to comment.user.name, user_path(comment.user.id) %>
        </div>
        <div><%= comment.created_at.strftime('%Y/%m/%d') %></div>
      </div>
      <div class="comment-text">
        <p><%= comment.comment %></p>
        <% if current_user == comment.user %>
          <p><%= link_to "削除", post_post_comments_path(comment.id), method: :delete, data: { confirm: '本当に消しますか?'}, remote: true %></p>
        <% end %>
      </div>
    </section>
  </div>
<% end %>

app/views/posts/_favorite.html.erb
<% if post.favorited_by?(current_user) %>
  <%= link_to post_favorites_path(post), method: :delete, remote: true do %>
    <%= icon('fas', 'heart', class: 'favorite') %>
  <% end %>
  <%= post.favorites.count %>
<% else %>
  <%= link_to post_favorites_path(post), method: :post, remote: true do %>
    <%= icon('far', 'heart', class: 'favorite') %>
  <% end %>
    <%= post.favorites.count %>
<% end %>

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: "form-control", rows: "6" %>
  </div>

  <div class="form-group">
    <lablel>画像<span class="image-label-help">--任意</span></lablel>
    <%= f.attachment_field :image %>
  </div>

  <%= f.submit "作成する" , class: "btn btn-primary" %>
<% end %>

<diV class="back-page"><%= link_to "戻る", :back %></diV>

app/views/posts/_index.html.erb
<table class="table table-hover post-index">
  <tbody>
    <% posts.each do |post| %>
    <td>
      <%= attachment_image_tag(post.user, :pro_image, :fill, 50, 50, fallback: "登録のピクトアイコン1.jpeg", size: "50x50") %>
      <span style="font-size: 30px;"><%= link_to post.title, post_path(post.id) %></span> 
      
      <div class="posts-info">
        <span style="float: left"><%= link_to post.user.name, user_path(post.user) %>が作成</span>
        <div style="text-align: right">
          <%= post.created_at.strftime('%Y/%m/%d') %>
          <%= icon('fas', 'heart') %><%= post.favorites.count %>
          <%= icon('far', 'comment-dots')%><%= post.post_comments.count %>
        </div>
      </div>
    </td>
  </tbody>
  <% end %>
</table>
<div class="text-center"><%= paginate posts, class: "paginate", theme: 'my_custom_theme' %></div>

app/views/posts/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1">

      <h1>記事編集</h1>

      <%= render "layouts/errors", obj: @post %>

      <%= render "posts/form", post: @post %>

    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container">
  <div class="row">
    <h1>記事一覧</h1>

    <div class="posts-new-button-index"><%= link_to "記事を作成する", new_post_path , class: "btn btn-info" %></div>

    <%= render "posts/index", posts: @posts %>

  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="row">
    
    <div class="col-xs-10 col-xs-offset-1">
      <h1>記事新規作成</h1>

      <%= render "layouts/errors" , obj: @post %>

      <%= render "posts/form", post: @post %>

    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
	<div class="row">
		<div class="center-block">
			<div class="col-xs-10 col-xs-offset-1">
				<h1><%= @post.title %></h1>

				<span class="post-user-info">
					<%= link_to user_path(@post.user.id) do %>
						<%= attachment_image_tag(@post.user, :pro_image, :fill, 50, 50, fallback: "登録のピクトアイコン1.jpeg", size: "50x50") %>
						<%= @post.user.name %>
					<% end %>
					さんがこの記事を作成しました
				</span>

				<div class="post-create-time"><%= @post.created_at.strftime('%Y/%m/%d') %></div>

				<main class="post-text">
					<%= simple_format(@post.body) %><br>
					<div class="post-image"><%= attachment_image_tag @post, :image, :fill, 200, 200 %></div>

						<div class="post-edit-destroy">
							<!-- お気に入りボタン -->
							<% if user_signed_in? %>
								<div class="post_favorite_<%= @post.id %>">
									<%= render "posts/favorite", post: @post %>
								</div>
							<% end %>
							
							<% if user_signed_in? && @post.user_id == current_user.id %>
									<%= link_to "編集する", edit_post_path(@post), class: "btn btn-default" %>
									<%= link_to "削除する", post_path(@post), method: :delete, data: { confirm: '本当に消しますか？'}, class: "btn btn-link" %>
							<% end %>
						</div>
				</main>
				
				<div class="clearfix">
					<% if user_signed_in? %>
						<%= form_with model:[@post, @post_comment], data: {remote: true} do |f| %>
							<div class="form-group">
								<%= f.text_area :comment, class: "form-control", rows: "5" %>
							</div>
							<%= f.submit "コメントする" , class: "btn btn-primary" %>
						<% end %>
					<% else %>
						<div class="session-alert">
							<%= link_to "ログイン", new_user_session_path %>してコメントする
							<div>会員登録がお済みでない方は<%= link_to "こちら", new_user_registration_path %></div>
							
						</div>
					<% end %>
				</div>
				

					<div class="comment">
						<h1>コメント一覧</h1>
							<%= render "posts/comment", post_comments: @post.post_comments, post: @post %>
					</div>
			</div>
		</div>
	</div>
</div>

app/views/users/_index.html.erb
<table class="table">
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td>
            <%= link_to user_path(user) do %>
              <%= attachment_image_tag(user, :pro_image, :fill, 100, 100, fallback: "登録のピクトアイコン1.jpeg", size: "50x50") %>
              <%= user.name %>
            <% end %>
            <div>
              <%= user.introdution %>
            </div>
            <!-- フォローボタン -->
            <% if current_user != user %>
              <% if current_user.following?(user) %>
                <%= link_to user_relationships_path(user.id), method: :delete, remote: true do %>
                  <button class="btn btn-default"><%= icon('fas', 'user-check') %>フォローを外す</button>
                <% end %>
              <% else %>
                <%= link_to user_relationships_path(user.id), method: :post, remote: true do %>
                  <button class="btn btn-default"><%= icon('fas', 'user-plus') %>フォローする</button>
                <% end %>
              <% end %>
            <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
  <%= paginate users, class: "paginate" %>
</table>

app/views/users/_profile.html.erb
<div class="col-sm-4">
    <div class="profile">
      <%= attachment_image_tag(user, :pro_image, :fill, 200, 200, fallback: "登録のピクトアイコン1.jpeg", size: "200x200") %>
    </div>
    

    <table class="table table-bordered">
      <tbody>
        <tr>
          <td><label><%= user.name %></label></td>
        </tr>
        <tr>
          <td><%= user.introdution %></td>
        </tr>
      </tbody>
    </table>
    <% if current_user == user %>
      <div class="posts-new-button">
        <%= link_to new_post_path do %>
          <button class="btn btn-info"><%= icon('fas', 'plus') %> 記事を作成する</button>
        <% end %>
      </div>
    <% end %>

    <!-- フォローボタン -->
    <% if current_user != user %>
      <% if current_user.following?(user) %>
        <%= link_to user_relationships_path(user.id), method: :delete do %>
          <button class="btn btn-default"><%= icon('fas', 'user-check') %>フォローを外す</button>
        <% end %>
      <% else %>
        <%= link_to user_relationships_path(user.id), method: :post do %>
          <button class="btn btn-default"><%= icon('fas', 'user-plus') %>フォローする</button>
        <% end %>
      <% end %>
    <% end %>

  </div>

app/views/users/_settings.html.erb
<table class="table table-bordered">
  <caption>登録情報</caption>
  <tbody>
    <tr>
      <td><%= user.name %></td>
    </tr>
    <tr>
      <td><%= user.email %></td>
    </tr>
    <tr><td><%= user.introdution %></td></tr>
    <tr>
      <td>
        <%= link_to edit_user_path(user) do %>
          <button class="btn btn-link"><%= icon('fas', 'cog') %>登録情報の変更</button>
        <% end %>
      </td>
    </tr>
  </tbody>
</table>


<div class="user-delete-button">
  <%= link_to "退会する", withdraw_user_path(user), class: "btn btn-danger" %>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h1 class="title-edit">登録情報変更</h1>

      <%= form_for(@user) do |f| %>
        <%= render "layouts/errors", obj: @user %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name , class: "form-control" %>
        </div>
        <div class="form-group">
           <%= f.label :email %>
           <%= f.email_field :email , class: "form-control" %>
        </div>
        <div class="form-group">
           <%= f.label :introdution %><span class="image-label-help">--任意</span>
           <%= f.text_area :introdution, class: "form-control", rows: "3" %>
        </div>
        <div class="form-group">
            <%= f.label :pro_image %><span class="image-label-help">--任意</span>
            <%= f.attachment_field :pro_image %>
        </div>
        <div class="action"><%= f.submit "変更する" , class: "btn btn-primary btn-block center-block" %></div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="row">

	<%= render "users/profile", user: @user %>

		<div class="col-sm-7">

			<div class="wrap">
				<ul class="nav nav-tabs nav-pills">
					<li><a href="#users-posts" data-toggle="tab" class="active">記事</a></li>
					<li><a href="#followings" data-toggle="tab">Follow</a></li>
					<li><a href="#bookmark" data-toggle="tab">ブックマーク</a></li>
					<% if @user == current_user %>
						<li><a href="#setting" data-toggle="tab">設定</a></li>
					<% end %>
				</ul>
			</div>

			<div class="tab-content">
					<div id="users-posts" class="tab-pane active">
						<%= render "posts/index", posts: @posts %>
					</div>

					<div id="followings" class="tab-pane">
						<div>
							<h3>フォロー中のユーザー</h3>
							<%= render "users/index" , users: @users %>
						</div>
						<div>
							<h3>フォロワー</h3>
							<%= render "users/index", users: @followers %>
						</div>
					</div>

					<div id="bookmark" class="tab-pane">
						<%= render "posts/index", posts: @favorites %>
					</div>

					<div id="setting" class="tab-pane">
						<%= render "users/settings", user: @user %>
					</div>

			</div>
		</div>
	</div>
</div>

app/views/users/withdraw.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <div class="center-block">
        <h1 style="margin-bottom: 25px;">退会申請</h1>

        <div class="panel panel-danger">
          <div class="panel-heading"><h4>ご注意</h4></div>
          <div class="panel-body">
            退会すると、記事の作成、コメントの投稿、お気に入り機能、フォロー機能等が使用できなくなります。
          </div>
        </div>

        <div class="delete-action">
          <% if user_signed_in? && @user.id == current_user.id %>
            <div class="delete-button"><%= link_to "キャンセル", user_path(@user.id), class: "btn btn-default" %></div>
            <div class="delete-button"><%= button_to "退会", user_path(@user.id), method: :delete, "data-confirm" => "本当に退会しますか？" , class: "btn btn-danger " %></div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>